<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220612135950 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add rep_log table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rep_log (autogenerated_id INT AUTO_INCREMENT NOT NULL, id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', reps INT NOT NULL, label VARCHAR(255) NOT NULL, weight INT NOT NULL, UNIQUE INDEX UNIQ_A460CE79BF396750 (id), PRIMARY KEY(autogenerated_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE rep_log');
    }
}
