controllers:
    resource: ../src/Controller/
    type: annotation

api:
    resource: ../src/Controller/Api/
    type: annotation
    prefix: '/api'

api_users:
    resource: ../src/Controller/Api/Users
    type: annotation
    prefix: '/api/users'

api_login_check:
    path: /api/auth/token/login

gesdinet_jwt_refresh_token:
    path: /api/auth/token/refresh

kernel:
    resource: ../src/Kernel.php
    type: annotation
